#! /bin/sh
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 
pgrep -x sxhkd > /dev/null || sxhkd &	

if (xrandr -q | grep -E '\bDP-1 connected') then
    autorandr --change
    bspc wm -O eDP-1 DP-1
    bspc monitor eDP-1 -d 1 2 3 4
    bspc monitor DP-1 -d 5 6 7 8
else
    autorandr --change
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
fi

bspc monitor "$m" -o $*

bspc config border_width         5
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#F0C674"
bspc config focused_border_color "#F0C674"

bspc config presel_feedback_color "#595B82"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc config split_ratio          0.52

##BG##
feh --bg-fill ~/Изображения/wallpaper.jpg &

##NOTIFICATIONS##
dunst &

##POLYBAR##
sleep 5
~/.config/polybar/launch-poly.sh &

##KEYMAP##
setxkbmap -option grp:win_space_toggle ru,us & 
